import React from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View, type TextInputProps } from 'react-native';

export const colors={bg:'#0B0D10',panel:'#14181D',line:'#242A31',text:'#F5F7F9',muted:'#98A2AD',accent:'#A8F04F',danger:'#FF6B6B',warning:'#F4C95D'};
export function Screen({children,scroll=true}:{children:React.ReactNode;scroll?:boolean}){if(scroll)return <ScrollView style={s.screen} contentContainerStyle={s.content}>{children}</ScrollView>;return <View style={[s.screen,s.content]}>{children}</View>}
export function Title({children}:{children:React.ReactNode}){return <Text style={s.title}>{children}</Text>}
export function Label({children}:{children:React.ReactNode}){return <Text style={s.label}>{children}</Text>}
export function Body({children,muted=false}:{children:React.ReactNode;muted?:boolean}){return <Text style={[s.body,muted&&{color:colors.muted}]}>{children}</Text>}
export function Input(props:TextInputProps){return <TextInput placeholderTextColor={colors.muted} {...props} style={[s.input,props.style]}/>}
export function Button({title,onPress,disabled=false,kind='primary'}:{title:string;onPress:()=>void;disabled?:boolean;kind?:'primary'|'secondary'|'danger'}){return <Pressable disabled={disabled} onPress={onPress} style={({pressed})=>[s.button,kind==='secondary'&&s.secondary,kind==='danger'&&s.danger,disabled&&{opacity:.4},pressed&&{opacity:.75}]}><Text style={[s.buttonText,kind!=='primary'&&{color:colors.text}]}>{title}</Text></Pressable>}
export function Status({online,label}:{online:boolean;label?:string}){return <View style={s.status}><View style={[s.dot,{backgroundColor:online?colors.accent:colors.muted}]}/><Text style={s.statusText}>{label??(online?'ONLINE':'OFFLINE')}</Text></View>}
export function Divider(){return <View style={s.divider}/>}
export function Loading({label='Loading…'}:{label?:string}){return <View style={s.center}><ActivityIndicator/><Body muted>{label}</Body></View>}
export function Card({children}:{children:React.ReactNode}){return <View style={s.card}>{children}</View>}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:colors.bg},content:{padding:24,paddingBottom:60,gap:16},title:{color:colors.text,fontSize:38,lineHeight:42,fontWeight:'800',letterSpacing:-1},label:{color:colors.muted,fontSize:12,fontWeight:'700',letterSpacing:1.2,textTransform:'uppercase'},body:{color:colors.text,fontSize:16,lineHeight:23},input:{borderWidth:1,borderColor:colors.line,borderRadius:14,color:colors.text,paddingHorizontal:16,paddingVertical:14,fontSize:16,backgroundColor:colors.panel},button:{backgroundColor:colors.accent,minHeight:52,borderRadius:14,alignItems:'center',justifyContent:'center',paddingHorizontal:18},secondary:{backgroundColor:colors.panel,borderWidth:1,borderColor:colors.line},danger:{backgroundColor:'#402020'},buttonText:{color:'#101410',fontWeight:'800',fontSize:15},status:{flexDirection:'row',alignItems:'center',gap:8},dot:{width:9,height:9,borderRadius:10},statusText:{color:colors.text,fontSize:12,fontWeight:'800',letterSpacing:.7},divider:{height:1,backgroundColor:colors.line,marginVertical:6},center:{flex:1,alignItems:'center',justifyContent:'center',gap:12,padding:24},card:{backgroundColor:colors.panel,borderRadius:18,padding:18,gap:10,borderWidth:1,borderColor:colors.line}});
